---

# PLEASE COMMENT ON GITHUB IF THIS HELPS YOU OR IF YOU HAVE ISSUES/RECOMMENDATIONS!

- name: Update WSUS Client Settings
  hosts: all
  gather_facts: false
  tasks:
  
    - name: Set Registry Path
      set_fact:
        wu_reg_path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate'
        au_reg_path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU'

  
    - name: Update WSUS Client TargetGroup
      win_regedit:
        path: "{{ wu_reg_path }}"
        name: 'TargetGroupEnabled'
        data: 1
        type: dword
        
    - name: Update WSUS Client TargetGroup
      win_regedit:
        path: "{{ wu_reg_path }}"
        name: 'TargetGroup'
        data: "{{ wsus_target_group }}"
        type: string
        
    - name: Update WSUS Client WUServer
      win_regedit:
        path: "{{ wu_reg_path }}"
        name: 'WUServer'
        data: 'http://p-wsus01.gentex.com:8530'
        type: string
      register: wuserver_updated

    - name: Update WSUS Client WUStatusServer
      win_regedit:
        path: "{{ wu_reg_path }}"
        name: 'WUStatusServer'
        data: 'http://p-wsus01.gentex.com:8530'
        type: string
        
    - name: Update UseWUServer Registry Key
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'UseWUServer'
        data: 1
        type: dword
        state: present

    - name: Update NoAutoUpdate Registry Key
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'NoAutoUpdate'
        data: "{{ wsus_noautoupdate | default('1') }}" # 1 Disable, 0 Enable
        type: dword
        state: present

    - name: Update AUOptions Registry Key
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'AUOptions'
        data: "{{ wsus_auoptions | default('2') }}" # 2 = Notify before download. 3 = Automatically download and notify of installation. 4 = Automatically download and schedule installation. Only valid if values exist for ScheduledInstallDay and ScheduledInstallTime. 5 = Automatic Updates is required and users can configure it.
        type: dword
        state: present
 
    - name: Update Scheduled Day Registry Key
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'ScheduledInstallDay'
        data: "{{ wsus_scheduledinstallday }}"
        state: present
      when: wsus_auoptions == 4
       
    - name: Update Scheduled Time Registry Key
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'ScheduledInstallTime'
        data: "{{ wsus_scheduledinstalltime }}"
        state: present
      when: wsus_auoptions == 4
       
    - name: Remove Scheduled Day Registry Keys
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'ScheduledInstallDay'
        state: absent
      when: wsus_auoptions != 4
      
    - name: Remove Scheduled Time Registry Keys
      win_regedit:
        path: "{{ au_reg_path }}"
        name: 'ScheduledInstallTime'
        state: absent
      when: wsus_auoptions != 4

    - name: Register with WSUS Server
      win_command: wuauclt /detectnow
      when: wuserver_updated.data_changed
